before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec -f d -c
